const state={phase:1,index:0,attributeScores:{driver:0,analytical:0,amiable:0,expressive:0},selectedAttribute:null,subtypeScores:{},history:[]};
const $=function(s){return document.querySelector(s)};
function setAccent(attribute){document.documentElement.style.setProperty("--accent",(ATTRIBUTES[attribute]||ATTRIBUTES.driver).color)}
function snapshot(){return{phase:state.phase,index:state.index,attributeScores:Object.assign({},state.attributeScores),selectedAttribute:state.selectedAttribute,subtypeScores:Object.assign({},state.subtypeScores)}}
function leading(obj){return Object.entries(obj).sort(function(a,b){return b[1]-a[1]})[0][0]}
function currentEvent(){if(state.phase===1)return STEP1_EVENTS[state.index];var subs=ATTRIBUTE_SUBTYPES[state.selectedAttribute];return{title:STEP2_EVENTS[state.selectedAttribute][state.index],text:"守護者の気配が近くなる。あなたの中で、いちばん自然に動くものは？",choices:SUBTYPE_CHOICES.map(function(label,i){return[label,subs[i]]})}}
function renderEvent(){var event=currentEvent();var step=state.phase===1?state.index+1:11+state.index;var attr=state.selectedAttribute||leading(state.attributeScores);setAccent(attr);$("#chapterLabel").textContent=state.phase===1?"chapter 1":"chapter 2";$("#chapterTitle").textContent=state.phase===1?"迷宮の入口":ATTRIBUTES[state.selectedAttribute].label+"の奥部屋";$("#stepCounter").textContent=step+" / 20";$("#eventKind").textContent=state.phase===1?"event":"guardian event";$("#eventTitle").textContent=event.title;$("#eventText").textContent=event.text;$("#backButton").disabled=state.history.length===0;var list=$("#choiceList");list.innerHTML="";event.choices.forEach(function(choice){var b=document.createElement("button");b.className="choice-button";b.type="button";b.textContent=choice[0];b.addEventListener("click",function(){choose(choice[1])});list.append(b)});renderMap(step);renderMeters()}
function choose(value){state.history.push(snapshot());if(state.phase===1){state.attributeScores[value]+=1;if(state.index<STEP1_EVENTS.length-1){state.index+=1;renderEvent();return}state.selectedAttribute=leading(state.attributeScores);state.phase=2;state.index=0;state.subtypeScores={};ATTRIBUTE_SUBTYPES[state.selectedAttribute].forEach(function(s){state.subtypeScores[s]=0});renderEvent();return}state.subtypeScores[value]+=1;if(state.index<STEP2_EVENTS[state.selectedAttribute].length-1){state.index+=1;renderEvent();return}showResult()}
function showResult(){var subtype=leading(state.subtypeScores);var guardian=GUARDIANS.find(function(g){return g.attribute===state.selectedAttribute&&g.subtype===subtype});setAccent(guardian.attribute);$("#resultGuardian").style.setProperty("--guardian-color",ATTRIBUTES[guardian.attribute].color);$("#resultName").textContent=guardian.name;$("#resultLead").textContent=guardian.lead;$("#protects").textContent=guardian.protects;$("#strength").textContent=guardian.strength;$("#overworked").textContent=guardian.overworked;$("#safeForm").textContent=guardian.safeForm;$("#playScreen").classList.add("hidden");$("#resultScreen").classList.remove("hidden");$("#resultScreen").scrollIntoView({behavior:"smooth",block:"start"})}
function renderMap(step){var map=$("#miniMap");map.innerHTML="";for(var i=1;i<=20;i++){var c=document.createElement("div");c.className="map-cell"+(i<=step?" visited":"");map.append(c)}}
function renderMeters(){var scores=state.phase===1?state.attributeScores:state.subtypeScores;var max=Math.max(1,...Object.values(scores));var meter=$("#attributeMeter");meter.innerHTML="";Object.entries(scores).forEach(function(entry){var label=(ATTRIBUTES[entry[0]]||{label:entry[0]}).label;var row=document.createElement("div");row.className="meter-row";row.innerHTML="<span>"+label+"</span><i class='meter-track'><span style='width:"+(entry[1]/max*100)+"%'></span></i>";meter.append(row)})}
function startGame(){setAccent("driver");$("#introScreen").classList.add("hidden");$("#playScreen").classList.remove("hidden");renderEvent();$("#playScreen").scrollIntoView({behavior:"smooth",block:"start"})}
function restart(){state.phase=1;state.index=0;state.attributeScores={driver:0,analytical:0,amiable:0,expressive:0};state.selectedAttribute=null;state.subtypeScores={};state.history=[];setAccent("driver");$("#resultScreen").classList.add("hidden");$("#playScreen").classList.add("hidden");$("#introScreen").classList.remove("hidden");$("#introScreen").scrollIntoView({behavior:"smooth",block:"start"})}
function goBack(){var prev=state.history.pop();if(!prev)return;state.phase=prev.phase;state.index=prev.index;state.attributeScores=prev.attributeScores;state.selectedAttribute=prev.selectedAttribute;state.subtypeScores=prev.subtypeScores;$("#resultScreen").classList.add("hidden");$("#playScreen").classList.remove("hidden");renderEvent()}
function renderLibrary(){var grid=$("#guardianGrid");GUARDIANS.forEach(function(g){var card=document.createElement("article");card.className="guardian-card";card.style.setProperty("--accent",ATTRIBUTES[g.attribute].color);card.innerHTML="<div class='card-visual' aria-hidden='true'></div><h3>"+g.name+"</h3><p>"+ATTRIBUTES[g.attribute].label+" / "+g.lead+"</p>";grid.append(card)})}
function toast(text){$("#toast").textContent=text;$("#toast").classList.add("visible");setTimeout(function(){$("#toast").classList.remove("visible")},2200)}
async function copyResult(){var text="守護者: "+$("#resultName").textContent+"\n"+$("#resultLead").textContent+"\n守ってきたもの: "+$("#protects").textContent;try{await navigator.clipboard.writeText(text);toast("出会いを記録しました。")}catch(e){toast("記録できませんでした。")}}
$("#startButton").addEventListener("click",startGame);$("#backButton").addEventListener("click",goBack);$("#restartButton").addEventListener("click",restart);$("#againButton").addEventListener("click",restart);$("#copyButton").addEventListener("click",copyResult);renderLibrary();